# -*- coding: utf-8 -*-
"""AnaliseFinanceira.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WDgZZHI2lmTFY7NSFHZZuvR-GqViz0ar
"""

datas = []
lucPerd = []

with open('dados_financeiro.txt', 'r') as financas:
  lista = financas.readlines()
  for i in lista[1:]:
    mes = i.replace('\n', ' ')
    mes = mes.split(',')
    datas.append(mes[0])
    lucPerd.append(int(mes[1]))

variacao = []

for i in range(1, len(lucPerd)):
  var = lucPerd[i] - lucPerd[i-1]
  variacao.append(var)

variacao.insert(0, 0)

with open('relatorio.txt', 'w') as rel:
  rel.write('Analise Financeira\n')
  rel.write('-' * 25 + '\n')
  rel.write(f'Total de meses: {len(datas)}\n')
  rel.write(f'Total: $ {sum(lucPerd)}\n')
  rel.write(f'Variação da média: $ {sum(variacao) / (len(variacao) - 1) :.2f}\n')
  rel.write(f'Total: $ {sum(lucPerd)}\n')
  rel.write(f'Média: $ {sum(lucPerd) / len(lucPerd) : .2f} \n')
  rel.write(f'Maior aumento nos lucros: {datas[variacao.index(max(variacao))]} ($ {max(variacao)})\n')
  rel.write(f'Maior aumento nos lucros: {datas[variacao.index(min(variacao))]} ($ {min(variacao)})\n')

with open('relatorio.txt') as relatorio:
  print(relatorio.read())